### ISSUE TITLE
Improve the 5th step of the "Create Config" > Path to stat Files

### ISSUE THREAD

**Issue by LeafGithub** [Souldiv/JO-RP-System#1]
When you reach the 5th step it requires you to indicate the path to a **stats file** that the character should use, however, while any path could be used, it is recommended that you have the program search for a folder called stats, you could attach it with the program already.

As in for the folder and the stats file, you could create a script or separate program that creates a simple **.json** file with the stats template on them
```{
    "BASE":{
        "HP": 0,
        "CHAKRA": 0,
        "NINP": 0,
        "TAIP": 0,
        "GENP": 0,
        "SPD": 0
    },
    "DEF":{
        "TAID": 0,
        "NIND": 0,
        "GEND": 0,
        "POID": 0
    },
    "MISC":{
        "MS": 0,
        "NT": 0,
        "SS": 0,
        "CC": 0,
        "HE": 0,
        "ER": 0
    }
}
```

Then the **"Main.exe"** would automatically search for that browser and allow us to choose from the available files there
![sfg4gap 1](https://user-images.githubusercontent.com/19421019/66425533-ede89e00-e9dd-11e9-8442-fb2d7b09f180.png)

**Comment by Souldiv** [comment]
Done.
